version: '3'

services:

  controller:
    build: example_controller_python_px4/
    network_mode: ${STARLING_NETWORK_MODE:-bridge}

networks:
  default:
    external: true
    name: ${STARLING_NETWORK:-projectstarling_default}