version: '3'

services:

  controller:
    build: example_controller_python_ap/
    network_mode: ${STARLING_NETWORK_MODE:-host}
    depends_on:
      - mavros

networks:
  default:
    external: true
    name: ${STARLING_NETWORK:-projectstarling_default}